language: r
cache: packages

r_packages:
  - covr
  - roxygen2

r_github_packages:
  - NVE/FlomKart_ShinyApp
  - hafen/packagedocs

env:
  global:
    - GITHUB_REPO: "NVE/fitdistrib"
    - GITHUB_PAT

before_script:
  # install the pkg so it can be used as a vig builder (only necessary for packagedocs)
  - Rscript -e "devtools::document()"
  - Rscript -e "devtools::install()"
  - Rscript -e "packagedocs::build_vignettes()"
  - chmod +x ./_deploy.sh

script:
  - ./_deploy.sh

after_success:
 -  - Rscript -e 'library(covr); codecov()'
