language: r
cache: packages

r_packages:
  - covr

r_github_packages:
  - NVE/FlomKart_ShinyApp

env:
  global:
    - GITHUB_REPO: "NVE/fitdistrib"
    - GITHUB_PAT

#before_script:
#  - chmod +x ./_deploy.sh

# script:
#  
#  - ./_deploy.sh  

after_success:
 -  - Rscript -e 'library(covr); codecov()'
