# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
sudo: false
cache: packages
r_packages:
  - covr
- RNetCDF

r_github_packages:
- NVE/FlomKart

env:
  global:
    - GITHUB_REPO: "NVE/fitdistrib"
    - GITHUB_PAT

before_script:
  - chmod +x ./_deploy.sh

script:
  - ./_deploy.sh  
  
after_success:
  - Rscript -e 'library(covr); codecov()'
