language: r
cache: packages

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y netcdf-bin
  - sudo apt-get install -y nco
  - sudo apt-get install -y netcdf-doc
  - sudo apt-get install -y libnetcdf-dev
  - sudo apt-get install -y libnetcdf6
  - sudo apt-get install -y libapparmor1
  - sudo apt-get install -y libcurl4-openssl-dev
  - sudo apt-get install -y udunits-bin
  - sudo apt-get install -y libudunits2-dev

r_packages:
  - covr
  - RNetCDF

r_github_packages:
  - NVE/FlomKart

env:
  global:
    - GITHUB_REPO: "NVE/fitdistrib"
    - GITHUB_PAT

before_script:
  - chmod +x ./_deploy.sh

script:
  - ./_deploy.sh  
  
after_success:
  - Rscript -e 'library(covr); codecov()'
