---
title: "fitdistrib"
subtitle: "Fitting probability distributions"
author: ""
copyright: ""
output:
  packagedocs::package_docs:
    toc: true
    toc_collapse: false
redirect: http://NVE.github.io/fitdistrib
vignette: |
  %\VignetteIndexEntry{fitdistrib Documentation}
  %\VignetteEngine{packagedocs::redirect}
navpills: |
  <li class="active"><a href='index.html'>Docs</a></li>
  <li><a href='rd.html'>Package Ref</a></li>
  <li><a href='https://github.com/NVE/fitdistrib'>Github <i class='fa fa-github'></i></a></li>
---

```{r global_options, include=FALSE}
# R output pre blocks are styled by default to indicate output
knitr::opts_chunk$set(comment = NA)

# shorthand for rd_link() - see ?packagedocs::rd_link for more information
rdl <- function(x) packagedocs::rd_link(deparse(substitute(x)))
```

# What is the fitdistrib package? 

This package is a set a functions developed with the FlomKart flood frequency analysis project at NVE.
It allows estimating probability distribution parameters for the following distributions:

- GEV: Generalized Extreme Value
- GL: Generalized Logistics
- PEARSON: Three parameter Pearson distribution
- GAMMA distribution
- GUMBEL distribution

Four different estimation methods are available:

- MOM: method of moments
- Lmom: linear moments
- MLE: Maximum Likelyhood Estimation
- Bayes: Bayesian inference

The results of this package are used in the `FlomKart`package ([documentation](http://NVE.github.io/FlomKart) and [code](http://github.com/NVE/FlomKart)) to build 2 NetCDF files which can then be explored with the NASA's NetCDF viewer *[Panoply]*(http://www.giss.nasa.gov/tools/panoply/) or by our dedicated FlomKart shiny app ([documentation](http://NVE.github.io/FlomKart_ShinyApp) and [code](http://github.com/NVE/FlomKart_ShinyApp)).

# How was it coded?

In [Package Ref](http://NVE.github.io/fitdistrib/rd.html), you'll find the documentation of all the packaged functions.
This package uses the existing R packages `nsRFA`, `evd`, `ismev`, `fitdistrplus` and `stats`. The use of functions from those packages is adapted to our context. Some new fitting functions were also implemented when not already available. 
